AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "vendor/**/*"

Metrics/LineLength:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/FileName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/BarePercentLiterals:
  EnforcedStyle: percent_q

